FROM maven:latest AS build
LABEL authors="axerex"

WORKDIR /app
COPY pom.xml /app/
COPY src /app/src
RUN mvn clean package -DskipTests

FROM openjdk:17-jre-slim
WORKDIR /app
COPY --from=build /app/target/TemperatureConverter.jar /app/app.jar
EXPOSE 8080
CMD ["java", "-jar", "/app/app.jar"]