sonar.projectKey=myproject
sonar.projectName=untitled2
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.login=squ_55cc9ef93dccd39b737742e58fed405853acf7e5